"use strict";
exports.__esModule = true;
var MergeSort_1 = require("./MergeSort");
var QuickSort_1 = require("./QuickSort");
var Search_1 = require("./Search");
var test = require("./TestCases");
var sortedArray;
sortedArray = MergeSort_1["default"](test.case1);
console.log(Search_1["default"](sortedArray, -2932));
sortedArray = QuickSort_1["default"](test.case1);
console.log(Search_1["default"](sortedArray, -2932));
sortedArray = MergeSort_1["default"](test.case2);
console.log(Search_1["default"](sortedArray, 501));
sortedArray = QuickSort_1["default"](test.case2);
console.log(Search_1["default"](sortedArray, 501));
sortedArray = MergeSort_1["default"](test.case3);
console.log(Search_1["default"](sortedArray, 2086));
sortedArray = QuickSort_1["default"](test.case3);
console.log(Search_1["default"](sortedArray, 2086));
sortedArray = MergeSort_1["default"](test.case4);
console.log(Search_1["default"](sortedArray, 3879));
sortedArray = QuickSort_1["default"](test.case4);
console.log(Search_1["default"](sortedArray, 3879));
