# Generated by Django 2.2.6 on 2019-10-30 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song_mgt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='artist',
            new_name='artists',
        ),
        migrations.AlterUniqueTogether(
            name='song',
            unique_together={('title', 'artists')},
        ),
    ]
